### ISSUE TITLE
__attribute__((unused)) is a compile error in Visual C++

### ISSUE THREAD

**Issue by mcejp** [RyanBabij/Wildcat#3]
This line specifically: https://github.com/RyanBabij/Wildcat/blob/4599ed96fbc977f50a0b233010d40d52006ae7e4/Container/ArrayS3/ArrayS3.hpp#L292

In C++17, you can use the porable `[[maybe_unused]]`. There is a nice discussion of all the options here: https://stackoverflow.com/q/1486904/2524350

**Comment by RyanBabij** [comment]
Ah okay, I'll sort that out
